name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
   runs-on: ${{ matrix.os }}
   strategy:
     matrix:
      os: [windows-latest, ubuntu-latest, macos-latest]

   steps:
     - uses: actions/checkout@v2
      
     - name: Install dependencies
       run: |
            dotnet nuget add source "https://nuget.pkg.github.com/digitalcoyote/index.json" --name github --username digitalcoyote --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
            dotnet restore ./Src/NuGetDefense.Core.sln
     - name: Build
       run: dotnet build ./Src/NuGetDefense.Core.sln --configuration Release --no-restore
     - name: Test
       run: dotnet test ./Src/NuGetDefense.Core.sln --no-restore --verbosity normal
       
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v2
      
#      - name: Install dependencies
#        run: |
#             dotnet nuget add source "https://nuget.pkg.github.com/digitalcoyote/index.json" --name github --username digitalcoyote --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
#             dotnet restore ./Src/NuGetDefense.Core.sln
#             dotnet tool install Nuke.GlobalTool --global
#             dotnet tool install GitVersion.Tool --global
#      - name: Build
#        run: nuke --root ./
#      - name: Publish
#        run: dotnet test ./Src/NuGetDefense.Core.sln --no-restore --verbosity normal

