name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Install dependencies
      run: |
           dotnet nuget add source "https://nuget.pkg.github.com/digitalcoyote/index.json" --name github --username digitalcoyote --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
           dotnet restore ./Src/NuGetDefense.Core.sln
    - name: Build
      run: dotnet build ./Src/NuGetDefense.Core.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./Src/NuGetDefense.Core.sln --no-restore --verbosity normal
